### ISSUE TITLE
Inventory Tetris 모드와의 호환성 문제

### ISSUE THREAD

**Issue by 0ghost0-dev** [Kill00/SplitItems#2]
## 원 작성자
[jaelee1111](https://steamcommunity.com/profiles/76561198410133704)
## 내용
* #### 0.0.1 버전의 경우 선택한 아이템이 들어있는 인벤토리에서 같은 타입의 아이템을 모두 인식하는 방식이었으나 0.0.2 버전의 경우 선택한 아이템의 묶음만 인식하도록 변경되면서 발생한 호환성 이슈.

### 0.0.1
[ver0.0.1.webm](https://github.com/Kill00/SplitItems/assets/70481054/3b287b3f-3038-40cb-af90-ebed82861de6)
### 0.0.2
[ver0.0.2.webm](https://github.com/Kill00/SplitItems/assets/70481054/716cda02-9046-40b7-bcae-fae2220ff09f)

**Comment by Kill00** [comment]
동일 인벤토리 내에 아이템이 여러 개 있지만 선택한 블록의 아이템 개수가 한 개일 때 옵션이 표시되지 않는 버그 수정
